### ISSUE TITLE
Dont mangle key typos. 

### ISSUE THREAD

**Issue by aaroncrespo** [Carthage/Commandant#104]
https://github.com/Carthage/Carthage/issues/1926

I think for the sake of better error messages Commandant should not try and convert flags to a set

https://github.com/Carthage/Commandant/blob/903eaec12f3a68782496065dcc68393b8ab1b4bd/Sources/Commandant/ArgumentParser.swift#L75

It will mangle a `--key` typo and produce confusing errors. 

If flags are passed as used ex:
```
$ carthage update -platform
Unrecognized arguments: -armpfolt
```
Should become
```
$ carthage update -platform
Unrecognized arguments: -platform
```

**Comment by mdiep** [comment]
That's only done if there's a single `-`, which denotes a single-letter flag/argument. That's how basically all *nix tools work.

**Comment by aaroncrespo** [comment]
do all nix tools randomly the input in the error message?

**Comment by aaroncrespo** [comment]
This issue isn't about the fact that there is an error message. this issue is about the formatting and content of the error message.

**Comment by mdiep** [comment]
It looks like most tools bail on the first unknown option:

```
$ python -asenxtaboe 
Unknown option: -a
```

I'm not sure if that's better as it gives you less information.
