### ISSUE TITLE
Any objections to cutting a release?

### ISSUE THREAD

**Issue by jpsim** [Carthage/Commandant#121]
I'm happy to do it, just wondering if there was a reason why it hadn't been done since last May. /cc @mdiep @ikesyo

**Comment by mdiep** [comment]
Go for it. 👍

**Comment by jpsim** [comment]
Done: https://github.com/Carthage/Commandant/releases/tag/0.13.0

Although the deploy automation on Travis failed, so I ran the deploy commands locally to upload the framework zip.
