### ISSUE TITLE
Help message for Argument could be improved

### ISSUE THREAD

**Issue by benasher44** [Carthage/Commandant#128]
In realm/SwiftLint#1191, I'm adding an `Argument`. For an `Argument` initialized like this:
```
Argument(defaultValue: [""], usage: "list of paths to the files or directories to \(action)")
```

I get a help message that looks like this:
```
[[""]]
	list of paths to the files or directories to lint
```

It'd be nice if instead it looked more like this (to match arg interfaces in other cli tools):
```
[<paths…>]
	list of paths to the files or directories to lint
```

This may require the inclusion of a 3rd parameter to `Argument` called `variableName`.

**Comment by mdiep** [comment]
Want to open a PR for this? 🙂

**Comment by benasher44** [comment]
Done! I didn't think I'd have time to do this initially :)
