### ISSUE TITLE
`carthage checkout ` fails on using Commandant v0.8.3

### ISSUE THREAD

**Issue by norio-nomura** [Carthage/Commandant#54]
```sh
% carthage checkout
*** Checking out SWXMLHash at "2.1.0"
*** Checking out Result at "1.0.2"
*** Checking out xcconfigs at "0.8.1"
*** Checking out Commandant at "0.8.3"
A shell task failed with exit code 1:
fatal: reference is not a tree: fcb11a2cbf08e10806039b8f767ab9072115d04d
Unable to checkout 'fcb11a2cbf08e10806039b8f767ab9072115d04d' in submodule path 'Carthage/Checkouts/Quick'
```

It seems https://github.com/Quick/Quick/commit/fcb11a2cbf08e10806039b8f767ab9072115d04d is not exists on tree of Quick that referenced by Commandant v0.8.3.

https://github.com/jpsim/SourceKitten/issues/157

**Comment by mdiep** [comment]
I've been getting this too, and I'm not sure why. Deleting the root repository and recloning has fixed it for me when I've hit it. :confused:

**Comment by norio-nomura** [comment]
In working tree of Commandant, It can be fixed by `git submodule sync --recursive`.
But in one that depending to Commandant, it can't fix by `git submodule sync --recursive`. :cry:
Maybe I should file this to Quick…

**Comment by norio-nomura** [comment]
I resolved it with fetching Quick by tag in submodules.
```sh
% (cd Carthage/Checkouts/Commandant/Carthage/Checkouts/Quick; git fetch origin v0.9.0)
From https://github.com/Quick/Quick
 * tag               v0.9.0     -> FETCH_HEAD
% (cd Carthage/Checkouts/SourceKitten/Carthage/Checkouts/Commandant/Carthage/Checkouts/Quick; git fetch origin v0.9.0)
From https://github.com/Quick/Quick
 * tag               v0.9.0     -> FETCH_HEAD
```

Thanks,
