### ISSUE TITLE
Recursive commands

### ISSUE THREAD

**Issue by RahulKatariya** [Carthage/Commandant#74]
Is it possible to create recursive commands like below ?

```
Carthage iOS update
Carthage iOS bootstrap
Carthage Mac bootstrap
Carthage Mac update
```

or are you considering this in future release ?

What I am really trying to do is that I have 2 command line applications suppose `iOS` and `Mac` and I am making a super command line application with my name `rahulkatariya` so that I can use the following commands

`rahulkatariya ios <subcommand> <arguments>`
`rahulkatariya mac <subcommand> <arguments>`

**Comment by mdiep** [comment]
That's not currently possible, no.

**Comment by RahulKatariya** [comment]
A workaround I saw is to use command redundantly with the subcommand like

verb = "iOS update"
verb = "iOS bootstrap"
