### ISSUE TITLE
Release configuration build fails on Linux

### ISSUE THREAD

**Issue by scottrhoyt** [Carthage/Commandant#82]
It appears that `Commandant` will not successfully build in the release configuration on Linux. This looks to be due to `Quick` being built and referencing the non-existent (in release) `XCTest` module. This does not happen on macOS, likely due to the conditional inclusion of `Quick` in `Package.swift`. I believe there are some workarounds for Test-only dependencies using SPM, but I am curious as to whether or not `Quick` is needed on Linux at all if it is not being included on macOS.

**Steps to reproduce:**

* Create a new trivial package (e.g. `swift-package init --type executable`)
* Add `Commandant` to `Package.swift`
* Build in release configuration using `swift build -c release`

**Expected Results**

Package builds without errors.

**Actual Results**

Package fails to build with linker errors related to `Quick` referencing `XCTest`.

**Comment by mdiep** [comment]
I think Quick needs to come out of the `Package.swift` and needs to be added directly to the CI job [like ReactiveSwift does](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/.travis.yml).

Any chance you'd be interested in opening a PR to fix it?

**Comment by scottrhoyt** [comment]
Thanks for taking care of that. I was going to open up a PR myself but you beat me to it. Next time!
