### ISSUE TITLE
Passing a Switch key is ignored if the Switch contains a flag

### ISSUE THREAD

**Issue by NatanRolnik** [Carthage/Commandant#95]
Imagine the following scenario:

`Switch(flag: "f", key: "force", usage: "Whether to force")`

Surprisingly, calling `my-tool do something -f` has a different than `my-tool do something --force`. The former one works, while the latter fails.

However, if the switch is initialized with: `Switch(flag: nil, key: "force", usage: "Whether to force")`, without a flag, `--force` works.

This is due to a (what I understand as a) bug in the [Switch `<|` function](https://github.com/Carthage/Commandant/blob/master/Sources/Commandant/Switch.swift#L56):

```swift
case let .arguments(arguments):
    var enabled = arguments.consume(key: option.key)

    if let flag = option.flag {
        enabled = arguments.consumeBoolean(flag: flag)
    }
    return .success(enabled)
```

You can see that, when a flag exists, it will always read try to read if the flag was passed, and this will override the value if the key was passed.

I've [opened a PR](https://github.com/Carthage/Commandant/pull/96/) with tests and the fix for them.

**Comment by mdiep** [comment]
Fixed by #96.
